# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

RUN apk add --no-cache curl bash

RUN curl -fsSL https://bun.sh/install | bash

RUN mv /root/.bun/bin/bun /usr/local/bin/
RUN chmod a+x /usr/local/bin/bun

ENV BUN_INSTALL="/usr/local"
ENV PATH="$BUN_INSTALL/bin:$PATH"

ARG USERNAME=runner
ARG USER_UID=1010
ARG USER_GID=$USER_UID

RUN adduser -D -u $USER_UID -h /home/$USERNAME $USERNAME
ENV HOME=/home/$USERNAME

WORKDIR $HOME/app
RUN chown -R $USERNAME:$USERNAME $HOME
USER $USERNAME

COPY package.json bun.lock ./

RUN bun install

COPY --chown=$USERNAME:$USERNAME . .

RUN bun run build

EXPOSE 8002

ENTRYPOINT [ "./entrypoint.sh" ]